int _isupper(int c);
int _isdigit(int);
int mul(int, int);
int _putchar(char);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int);
void print_diagonal(int);
void print_square(int size);
void print_triangle(int size);
void print_number(int n);
